[tool.poetry]
name = "pythonproject7"
version = "0.1.0"
description = ""
authors = ["imbon <i.m.bondarev@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
signals = "^0.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
